[package]
name = "visca-remote-joystick"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
gilrs = "0.11"
grafton-visca = "0.2"
watch = "0.2"

[dependencies.clap]
version = "4.5"
features = ["derive"]
